#!/usr/bin/env node
// Renders the live view of every task-flow run into the project's docs folder.
//
// Why this exists. A run chains seven phases in one invocation and can spend an
// hour inside `build`. From the outside that is a wall of tool calls: there is no
// way to tell which phase is running, which task it is on, or whether it banked a
// question. With more than one run in flight, in different sessions, it is worse.
//
// Why it is GENERATED and never written by the agent. The pipeline already has a
// hook (stop.js) whose whole reason for existing is that prose instructions drift.
// A dashboard the agent updates by hand drifts the same way, and a stale dashboard
// is worse than none because it is believed. So nothing here is transcribed: every
// line is derived from state.json and from the plan's own task headings. That is
// also what keeps the promise that this is not a second copy of the plan.
//
// Nothing project-specific is hard-coded. The docs folder, the page language and
// where the runs live all come from the repository's .claude/task-flow.json,
// through config.js.

'use strict';

const fs = require('fs');
const path = require('path');
const { crossesLink, homeDir, homePath, isInside, loadConfig, projectKey } = require('./config.js');
const questionsData = require('./questions.js');

/** The stages a run passes through, in order. `phase` names the last one COMPLETED,
 *  so the stage in flight is the one that follows it. */
const PHASES = ['idea', 'spec', 'plan', 'build', 'tests', 'harden', 'review'];

/** A slug becomes a directory name and a file name. Anything outside this cannot. */
const SAFE_SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

const GENERATED_BY = 'render-run.js';

/** Where the pages and the questions live inside the docs folder. Fixed, and not
 *  translated: a folder that changed name with the language would break every
 *  link the day someone switched it. */
const RUNS_DIR = 'runs';
const RUNS_ARCHIVE = 'finished';
const QUESTIONS_DIR = 'questions';
const QUESTIONS_ARCHIVE = 'resolved';
const QUESTIONS_SUFFIX = '_questions.md';

// --- the words on the page ---------------------------------------------------

/** Every sentence the page prints, per page language (config.js decides which
 *  language a project gets; anything without a table here is English). */
const STRINGS = {
  en: {
    generatedNote: (by) => [
      `> Generated by \`${by}\`. **Do not edit by hand** - the next render`,
      "> overwrites it. The truth is in the run's `state.json`.",
    ],
    status: {
      done: 'finished',
      doneWaiting: 'waiting on you',
      blocked: 'stopped - waiting for an answer',
      failed: 'stopped - red tests',
      running: 'running',
      paused: 'paused',
    },
    allDone: '**All phases complete.**',
    allDoneWaiting: '**All phases complete.** It stays here because it has questions to answer.',
    phaseLine: (n, total, phase, taskPart) => `**Phase ${n} of ${total} · ${phase}**${taskPart}`,
    taskPart: (i, total) => ` · task ${i} of ${total}`,
    now: '**Now:**',
    phaseOverride: (phase) => [
      `> ⚠️ \`state.json\` says \`phase: "${phase}"\`, which on this page means`,
      '> "that phase is finished" - but the cursor still has tasks to do, so the page',
      '> followed the cursor. While the *build* runs, `phase` stays on the previous phase.',
    ],
    auto: 'auto mode',
    updated: (when) => `updated ${when}`,
    noPr: 'PR —',
    phasesHeading: '## Phases',
    approved: (who, when) => `· approved by ${who}${when ? ` on ${when}` : ''}`,
    here: '← here',
    tasksHeading: '## Tasks',
    doneOf: (done, total) => `${done} of ${total}`,
    skippedCount: (n) => `${n} skipped`,
    pendingCount: (n) => `${n} pending`,
    skipped: 'skipped',
    pendingAnswer: 'waiting for an answer',
    cursorNotATask: (cursor) => `The \`buildCursor\` does not name one of these tasks: ${cursor}`,
    cursorNoTasks: (cursor) => `Cursor on ${cursor}. The plan declares no tasks in numbered headings.`,
    questionsHeading: '## Questions',
    questionsLink: 'questions',
    openQuestions: (n) => `⚠️ **${n} to answer**`,
    noneOpen: 'None to answer',
    noneYet: 'None so far.',
    pendingDecisions: (n) => `Decisions taken alone, waiting for review: ${n} (the ceiling is 3).`,
    otherArtifacts: '## Other artifacts',
    outcome: '## Outcome',
  },
  'pt-PT': {
    generatedNote: (by) => [
      `> Documento gerado por \`${by}\`. **Não editar à mão** — a próxima`,
      '> escrita apaga as alterações. A verdade está no `state.json` da run.',
    ],
    status: {
      done: 'terminada',
      doneWaiting: 'à espera de ti',
      blocked: 'parada — à espera de resposta',
      failed: 'parada — testes vermelhos',
      running: 'a correr',
      paused: 'em pausa',
    },
    allDone: '**Todas as fases concluídas.**',
    allDoneWaiting: '**Todas as fases concluídas.** Fica aqui porque tem questões por responder.',
    phaseLine: (n, total, phase, taskPart) => `**Fase ${n} de ${total} · ${phase}**${taskPart}`,
    taskPart: (i, total) => ` · tarefa ${i} de ${total}`,
    now: '**Agora:**',
    phaseOverride: (phase) => [
      `> ⚠️ O \`state.json\` diz \`phase: "${phase}"\`, que nesta página significa`,
      '> «essa fase está concluída» — mas o cursor ainda tem tarefas por fazer, por isso a',
      '> página seguiu o cursor. Enquanto o *build* corre, `phase` fica na fase anterior.',
    ],
    auto: 'modo auto',
    updated: (when) => `actualizado ${when}`,
    noPr: 'PR —',
    phasesHeading: '## Fases',
    approved: (who, when) => `· aprovado por ${who}${when ? ` em ${when}` : ''}`,
    here: '← aqui',
    tasksHeading: '## Tarefas',
    doneOf: (done, total) => `${done} de ${total}`,
    skippedCount: (n) => `${n} ${n === 1 ? 'saltada' : 'saltadas'}`,
    pendingCount: (n) => `${n} ${n === 1 ? 'pendente' : 'pendentes'}`,
    skipped: 'saltada',
    pendingAnswer: 'pendente resposta',
    cursorNotATask: (cursor) => `O \`buildCursor\` não nomeia uma destas tarefas: ${cursor}`,
    cursorNoTasks: (cursor) => `Cursor em ${cursor}. O plano não declara tarefas em cabeçalhos numerados.`,
    questionsHeading: '## Questões',
    questionsLink: 'questões',
    openQuestions: (n) => `⚠️ **${n} por responder**`,
    noneOpen: 'Nenhuma por responder',
    noneYet: 'Nenhuma até agora.',
    pendingDecisions: (n) => `Decisões tomadas sozinho, à espera de revisão: ${n} (o tecto é 3).`,
    otherArtifacts: '## Outros artefactos',
    outcome: '## Desfecho',
  },
};

const stringsFor = (lang) => STRINGS[lang] || STRINGS.en;

// --- small helpers ---------------------------------------------------------

const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));

const exists = (file) => {
  try {
    fs.accessSync(file);
    return true;
  } catch {
    return false;
  }
};

/** Rejects a path that escapes the directory it is supposed to sit in. The slug is
 *  already validated; this is the second lock, because the cost of being wrong here
 *  is a file moved somewhere in the user's notes. */
function assertInside(dir, candidate) {
  const root = path.resolve(dir);
  const target = path.resolve(candidate);
  if (target !== root && !target.startsWith(root + path.sep)) {
    throw new Error(`refusing to touch ${target}: outside ${root}`);
  }
  // A link inside the folder can lead anywhere; the text of the path says nothing then.
  if (crossesLink(root, target)) throw new Error(`refusing to touch ${target}: it goes through a link`);
  return target;
}

/** Resolves a path that came out of state.json against the docs folder, or returns
 *  null if it points outside it. Every artifact path in state.json is an INPUT: the
 *  file is written by an agent, edited by hand, and committed. A `../../..` in it
 *  would otherwise let this script read any file on the machine and paste what it
 *  finds into a page.
 *
 *  An absolute path is accepted when it lands inside the docs folder, and refused
 *  when it does not - the same test a relative one gets, because it is the same
 *  question. Refusing every absolute path outright looks safer and is not: agents
 *  do write absolute paths, and a run whose every artifact came back null renders a
 *  page with no links that claims the plan has no tasks - a silent blanking. The
 *  containment check is what does the protecting. */
function resolveInsideDocs(docsDir, candidatePath) {
  if (!candidatePath || typeof candidatePath !== 'string') return null;
  try {
    const joined = path.isAbsolute(candidatePath)
      ? candidatePath
      : path.join(docsDir, candidatePath);
    return assertInside(docsDir, joined);
  } catch {
    return null;
  }
}

/** `yyMMdd`, the date prefix of dated documents. */
function datePrefix(date) {
  const yy = String(date.getFullYear()).slice(2);
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  return `${yy}${mm}${dd}`;
}

/** A bare `yyyy-MM-dd`. Told apart from a real timestamp because the two cannot be
 *  rendered the same way. */
const DATE_ONLY = /^(\d{4})-(\d{2})-(\d{2})$/;

/** `dd/MM hh:mm`, or `dd/MM` when the value carries no time of day.
 *
 *  A date with no time is not midnight, it is an unknown hour - and printing it as
 *  one is worse than printing nothing, because `01:00` reads as a measurement. It
 *  is not even midnight: `new Date('2026-09-23')` is UTC, so east of Greenwich a
 *  bare date comes out an hour or more into the next day. */
function shortDateTime(iso) {
  if (typeof iso === 'string') {
    const dateOnly = DATE_ONLY.exec(iso.trim());
    if (dateOnly) return `${dateOnly[3]}/${dateOnly[2]}`;
  }
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return null;
  const dd = String(date.getDate()).padStart(2, '0');
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const hh = String(date.getHours()).padStart(2, '0');
  const mi = String(date.getMinutes()).padStart(2, '0');
  return `${dd}/${mm} ${hh}:${mi}`;
}

// --- reading the run -------------------------------------------------------

/** The `yyMMdd` prefix a run's own artifacts already carry: `specs/260908_<slug>.md`.
 *  Preferred in that order because the spec is the first artifact the RUN produces -
 *  the idea is the user's and may be days older. */
function prefixFromArtifacts(artifacts = {}) {
  for (const key of ['spec', 'plan', 'idea']) {
    const value = artifacts[key];
    if (typeof value !== 'string') continue;
    const match = /(?:^|[\\/])(\d{2})(\d{2})(\d{2})_/.exec(value);
    if (match) return `${match[1]}${match[2]}${match[3]}`;
  }
  return null;
}

/** The `yyMMdd` prefix of the run's page. `created` first; then the prefix its own
 *  artifacts already carry; and only then the birth of state.json.
 *
 *  The file's own timestamp is last for a reason: inside a git worktree every
 *  checked-out file is born the day the worktree was made, so a run rendered from a
 *  worktree would be dated today. Only the file NAME depends on this, but a name
 *  that says the wrong week is exactly the kind of small lie that makes a dashboard
 *  stop being trusted. */
function runCreatedPrefix(state, statePath) {
  if (state.created) {
    const declared = new Date(state.created);
    if (!Number.isNaN(declared.getTime())) return datePrefix(declared);
  }
  const fromArtifacts = prefixFromArtifacts(state.artifacts);
  if (fromArtifacts) return fromArtifacts;

  const stats = fs.statSync(statePath);
  const born = stats.birthtime && stats.birthtime.getTime() > 0 ? stats.birthtime : stats.mtime;
  return datePrefix(born);
}

/** A task heading in a plan: an id, a separator, a title. Plans number tasks `T1`,
 *  `T0.5`, or per slice `A1`..`A8` / `B1`..`B5`, so the id is one or two capitals and
 *  a number, optionally with decimal parts - as many as needed, because a task over
 *  the size cap is split into `<id>.1`, `<id>.2` (SKILL.md §4), and a task that
 *  arrived split from the idea (`T11.8`) splits again (`T11.8.1`).
 *
 *  A lower-case letter may follow, because that is how a run names a task it inserts
 *  mid-flight (`T4b` between `T4` and `T5`); without it those tasks would be the
 *  ones the page could not see. One letter and no more - `T6bis` is a title, not an
 *  id.
 *
 *  The separator is required, and that is what keeps `## Overview`, `## Risks` and
 *  `## Checkpoint A — before PR A` out: a checkpoint is not a task and must never be
 *  counted as one. */
const TASK_HEADING = /^##\s+([A-Z]{1,2}\d+(?:\.\d+)*[a-z]?)\s*[·:–—-]\s+(.+)$/;

/** The heading of the section where a run writes the tasks it finds mid-run
 *  (SKILL.md §4), in every language a plan may be written in. Matched on the name
 *  alone, so a plan written in one language keeps rendering after a switch. */
const DISCOVERED_HEADING = /^##\s+(?:Discovered tasks|Tarefas descobertas)\b/i;

/** A task found mid-run: a top-level list item, not a heading. */
const DISCOVERED_TASK = /^- \[([ xX])\]\s+\*\*([A-Z]{1,2}\d+(?:\.\d+)*[a-z]?)\*\*\s*[·:–—-]\s+(.+)$/;
const CHECKBOX = /^- \[([ xX])\]/;

/** The tasks of a plan, in the order the plan declares them: every task heading,
 *  then the items of the discovered-tasks section.
 *
 *  Each task also carries the plan's own verdict on it. A task that has landed
 *  gets a state line - the first non-blank line under its heading, a checkbox
 *  (`- [x] **Done** — build …`). A task still to do opens with its description
 *  instead, so a ticked checkbox further down its section is an acceptance
 *  criterion and says nothing about the task. `stated` records whether the plan
 *  keeps state lines at all; a plan without any is still counted from the cursor.
 *
 *  Why the plan and not only the cursor: a cursor parked on a discovered task (a
 *  list item, not a heading) is invisible to a heading parser, and a page counting
 *  from the cursor alone then shows every task unticked. */
function readPlanTasks(planPath) {
  if (!planPath || !exists(planPath)) return [];
  const tasks = [];
  let awaitingStateLine = null;
  let inDiscovered = false;
  for (const raw of fs.readFileSync(planPath, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    const heading = TASK_HEADING.exec(line);
    if (heading) {
      // The title is printed on the page: plain text, like everything else read from a file.
      awaitingStateLine = { id: heading[1], title: plainText(heading[2], 160), ticked: false, stated: false };
      tasks.push(awaitingStateLine);
      inDiscovered = false;
      continue;
    }
    if (/^##\s/.test(line)) {
      awaitingStateLine = null;
      inDiscovered = DISCOVERED_HEADING.test(line);
      continue;
    }
    if (awaitingStateLine) {
      if (!line) continue;
      const box = CHECKBOX.exec(line);
      if (box) {
        awaitingStateLine.stated = true;
        awaitingStateLine.ticked = box[1].toLowerCase() === 'x';
      }
      awaitingStateLine = null;
      continue;
    }
    // An indented line is the continuation of the item above, not a new task.
    if (inDiscovered && raw === raw.trimStart()) {
      const found = DISCOVERED_TASK.exec(line);
      if (found) {
        tasks.push({
          id: found[2],
          title: plainText(found[3], 160),
          ticked: found[1].toLowerCase() === 'x',
          stated: true,
        });
      }
    }
  }
  return tasks;
}

/** This run's questions file, wherever it ended up: still open under questions/,
 *  already moved to questions/resolved/, or named in state.artifacts.questions. */
/** `yyMMdd_<slug><tail>`, exactly. A suffix match is not enough: for runs `a_b`
 *  and `b`, `260101_a_b.md` ends in `_b.md`, and run `b` would take it for its own. */
function datedName(slug, tail) {
  const literal = (text) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`^\\d{6}_${literal(slug)}${literal(tail)}$`);
}

function findQuestionsFile(docsDir, slug, state) {
  const declared = state.artifacts && state.artifacts.questions;
  if (declared) {
    // state.json is repository data: a path out of it is an input, not a fact.
    const candidate = resolveInsideDocs(docsDir, declared);
    if (candidate && exists(candidate)) {
      return { file: candidate, archived: path.basename(path.dirname(candidate)) === QUESTIONS_ARCHIVE };
    }
  }
  const ownName = datedName(slug, QUESTIONS_SUFFIX);
  for (const [dir, archived] of [
    [path.join(docsDir, QUESTIONS_DIR), false],
    [path.join(docsDir, QUESTIONS_DIR, QUESTIONS_ARCHIVE), true],
  ]) {
    if (!exists(dir)) continue;
    const hit = fs.readdirSync(dir).find((name) => ownName.test(name));
    if (hit) return { file: path.join(dir, hit), archived };
  }
  return null;
}

/** How many `- [ ]` are still waiting. A run only leaves the live folder at zero. */
function countOpenQuestions(file) {
  if (!file || !exists(file)) return 0;
  const matches = fs.readFileSync(file, 'utf8').match(/^\s*-\s\[\s\]/gm);
  return matches ? matches.length : 0;
}

// --- the document ----------------------------------------------------------

/** A relative markdown link from runs/ (or its archive) to a document. Deliberately
 *  not a `[[name]]`-style link: the idea and the spec of a run share a basename
 *  (260908_x.md in ideas/ and in specs/), so a name-only link would be ambiguous,
 *  and a plain relative link works in every markdown viewer. */
function link(label, docsRelativePath, depth) {
  if (!docsRelativePath) return null;
  const up = '../'.repeat(depth);
  // A file name is chosen by whoever wrote the file: a `)` in it would end the
  // link and turn the rest of the name into page markup. The characters that
  // can end or open markup are percent-encoded; everything else stays readable.
  const target = docsRelativePath
    .split(path.sep)
    .join('/')
    .replace(/[()[\]<>\s%]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase().padStart(2, '0')}`);
  return `[${label}](${up}${target})`;
}

/** Free text out of state.json, reduced to something that cannot forge page
 *  structure. Same reason the mode is a whitelist: state.json is written by agents
 *  and edited by hand, and this page is read as generated truth.
 *
 *  Headings, list items, block quotes and table rows all need a line start, so
 *  collapsing every run of whitespace removes that whole class at once. Brackets,
 *  angle brackets, pipes, backticks and asterisks go because a link, an HTML tag,
 *  a table cell or a code span needs no line of its own. URLs go whole: a reason
 *  is prose, and a renderer that auto-links bare URLs would turn one into a
 *  clickable link on a trusted page. The length cap is the last resort against a
 *  reason that tries to bury the rest of the section. */
function plainText(value, maxLength = 200) {
  if (typeof value !== 'string') return '';
  const flat = value
    .replace(/\s+/g, ' ')
    .replace(/\b[a-z][a-z0-9+.-]*:\/\/\S+/gi, '')
    .replace(/\bwww\.\S+/gi, '')
    .replace(/[[\]<>|`*]/g, '')
    .trim();
  return flat.length > maxLength ? `${flat.slice(0, maxLength - 1)}…` : flat;
}

/** A value shown inside a code span: plain text, and never empty, because an empty
 *  code span renders as two stray backticks. */
function codeSpan(value) {
  const text = plainText(value, 120);
  return text ? `\`${text}\`` : null;
}

/** A URL that may be pasted inside `[...](...)`. Anything else is refused rather
 *  than escaped: a single closing parenthesis in the value would end the link and
 *  everything after it would become page markup. A link target has no business
 *  containing whitespace, parentheses, brackets or quotes, so requiring their
 *  absence costs nothing real and closes the hole. */
function linkTarget(value) {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return /^https?:\/\/[^\s()<>[\]"']+$/.test(trimmed) ? trimmed : null;
}

/** The plan tasks this run consciously did not write, as id → reason.
 *
 *  Ids are matched against the plan and never echoed, the same discipline the
 *  buildCursor follows: state.json is repository data, so an id out of it is a
 *  lookup key, and a typo must not be able to invent a task line. */
function readSkippedTasks(state, tasks) {
  const known = new Set(tasks.map((task) => task.id));
  const skipped = new Map();
  if (!Array.isArray(state.skippedTasks)) return skipped;

  for (const entry of state.skippedTasks) {
    const id = entry && typeof entry === 'object' ? entry.id : entry;
    if (typeof id !== 'string' || !known.has(id)) continue;
    skipped.set(id, plainText(entry && typeof entry === 'object' ? entry.reason : ''));
  }
  return skipped;
}

/** The tasks an auto run parked because a question stayed unanswered after the
 *  question loop (SKILL.md §3), as id → the question. Same discipline as the
 *  skips: the id is a lookup key into the plan, and the question is reduced to
 *  plain text before it goes anywhere near the page. */
function readPendingTasks(state, tasks) {
  const known = new Set(tasks.map((task) => task.id));
  const pending = new Map();
  if (!Array.isArray(state.pendingTasks)) return pending;

  for (const entry of state.pendingTasks) {
    const id = entry && typeof entry === 'object' ? entry.id : entry;
    if (typeof id !== 'string' || !known.has(id)) continue;
    pending.set(id, plainText(entry && typeof entry === 'object' ? entry.question : ''));
  }
  return pending;
}

/** `openQuestions` matters only for a run that is otherwise finished. One with
 *  nothing open archives and is never read from runs/ again, so every page that
 *  stays there is either working or waiting on a person - and calling the second
 *  kind "finished" would turn the folder into a pile of finished work with no sign
 *  of which page wanted an answer. A blocked or running run keeps its own words:
 *  those already say what is happening. */
function statusLabel(state, openQuestions = 0, t = STRINGS.en) {
  const status = String(state.status || '').toLowerCase();
  if (state.phase === 'done' || status === 'done') {
    return openQuestions > 0 ? t.status.doneWaiting : t.status.done;
  }
  if (status === 'blocked') return t.status.blocked;
  if (status === 'failed') return t.status.failed;
  if (status === 'running') return t.status.running;
  return t.status.paused;
}

function buildDocument({ state, slug, tasks, questions, openQuestions, depth, artifacts = {}, created, lang = 'en' }) {
  const t = stringsFor(lang);
  const declaredIndex = PHASES.indexOf(state.phase);
  const isDone = state.phase === 'done';

  // A cursor that does not name one of the plan's tasks tells us nothing about
  // position. Some runs park free prose in there ("PR A and PR B both open"), and
  // guessing a task number from it would be the one thing this page must not do.
  const cursorIndex = state.buildCursor ? tasks.findIndex((task) => task.id === state.buildCursor) : -1;
  const located = cursorIndex >= 0;
  const landed = located ? cursorIndex + 1 : 0;

  // What the run decided not to write. Read before the task list is rendered
  // because it changes both the count and what "Now" is allowed to name.
  const skipped = readSkippedTasks(state, tasks);
  const pending = readPendingTasks(state, tasks);

  // A plan with state lines says itself which tasks landed (readPlanTasks); only
  // a plan without any is still counted from the cursor.
  const tracked = tasks.some((task) => task.stated);

  // A task the run skipped on purpose, or parked waiting on an answer, is never
  // done, whatever the phase says. Counting it as done would report a finished
  // run with cancelled tasks as "15 of 15".
  const isTaskDone = (task, index) =>
    !skipped.has(task.id) && !pending.has(task.id) &&
    (isDone || (tracked ? task.ticked : located && index < landed));
  const isOpen = (task, index) => !skipped.has(task.id) && !pending.has(task.id) && !isTaskDone(task, index);

  // "Now" steps over a skipped or pending task. Naming one would put the page in
  // contradiction with itself two lines further down, where the same task is
  // marked skipped or pending.
  let current = null;
  if (tracked) {
    // Runs park the cursor on the task being built, which has no ticked state
    // line yet; once it is ticked, the next open task after it is the one in flight.
    const fromCursor = located
      ? tasks.findIndex((task, index) => index >= cursorIndex && isOpen(task, index))
      : -1;
    const at = fromCursor >= 0 ? fromCursor : tasks.findIndex(isOpen);
    current = at >= 0 ? tasks[at] : null;
  } else if (located) {
    current = tasks.slice(landed).find((task) => !skipped.has(task.id) && !pending.has(task.id)) || null;
  }
  const cursorHasMore = located && tasks.some((task, index) => index > cursorIndex && isOpen(task, index));

  // `phase` names the last stage COMPLETED, and it is the field agents get wrong
  // most often: the natural thing to write while building is "build", which to
  // this page means the build is over. Nothing can usually tell the difference -
  // except here, where the cursor still names a task nobody has done. A run whose
  // build is finished has no unfinished task left to point at.
  //
  // So the cursor wins, and the page says in a line of its own that it overrode
  // the field. Silently correcting it would be the same failure in the other
  // direction: a page announcing the tests phase with the build on task 10 of 32,
  // and nothing anywhere saying the two disagreed.
  const BUILD_INDEX = PHASES.indexOf('build');
  // With state lines, only the cursor having tasks left after it is evidence: a
  // task the orchestrator forgot to tick is not the build still running.
  const buildStillOpen = !isDone && declaredIndex >= BUILD_INDEX &&
    (tracked ? cursorHasMore : current !== null);
  const completedIndex = buildStillOpen ? BUILD_INDEX - 1 : declaredIndex;

  const inFlight = isDone ? null : PHASES[completedIndex + 1] || PHASES[0];
  const inFlightNumber = inFlight ? PHASES.indexOf(inFlight) + 1 : PHASES.length;

  const out = [];
  out.push('---');
  out.push('type: run');
  out.push(`created: ${created}`);
  out.push(`slug: ${slug}`);
  out.push('---');
  out.push('');
  out.push(...t.generatedNote(GENERATED_BY));
  out.push('');
  out.push(`# ${slug} — ${statusLabel(state, openQuestions, t)}`);
  out.push('');

  if (isDone) {
    out.push(openQuestions > 0 ? t.allDoneWaiting : t.allDone);
  } else {
    // Counted from the task actually named below, not from the cursor: once
    // "Now" steps over a skipped task, a position derived from the cursor
    // disagrees with the task it is sitting next to.
    const currentIndex = current ? tasks.indexOf(current) : -1;
    const taskPart = currentIndex >= 0 ? t.taskPart(currentIndex + 1, tasks.length) : '';
    out.push(t.phaseLine(inFlightNumber, PHASES.length, inFlight, taskPart));
    const now = current ? `${current.id} · ${current.title}` : inFlight;
    out.push(`${t.now} ${now}`);
  }
  out.push('');

  // Safe to quote `state.phase` here: this line only exists when it matched one of
  // the seven fixed names, so there is nothing of the author's left in it.
  if (buildStillOpen) {
    out.push(...t.phaseOverride(state.phase));
    out.push('');
  }

  const meta = [];
  // An unattended run is exactly the one nobody is watching happen, so the page
  // has to say so before anything else on the line.
  //
  // Decided from the value, never echoed. state.json is written by agents and
  // edited by hand, and this page is read as generated truth: a mode carrying
  // markdown of its own could forge a heading or a PR link on it. Comparing
  // against a fixed string makes that impossible rather than unlikely, and an
  // unrecognised mode - including a missing one - is attended.
  if (String(state.mode || '').trim().toLowerCase() === 'auto') meta.push(t.auto);
  const updated = shortDateTime(state.updated);
  if (updated) meta.push(t.updated(updated));
  const branch = codeSpan(state.branch);
  if (branch) meta.push(`branch ${branch}`);
  const prUrl = linkTarget(state.pr);
  meta.push(prUrl ? `[PR](${prUrl})` : t.noPr);
  out.push(meta.join(' · '));
  out.push('');

  // --- phases
  out.push(t.phasesHeading);
  const artifactFor = { idea: artifacts.idea, spec: artifacts.spec, plan: artifacts.plan };
  PHASES.forEach((phase, index) => {
    const done = isDone || index <= completedIndex;
    const here = phase === inFlight;
    const bits = [`- [${done ? 'x' : ' '}] ${here ? `**${phase}**` : phase}`];
    const artifact = link(phase, artifactFor[phase], depth);
    if (artifact) bits.push(`— ${artifact}`);
    const approver = plainText(state.approvedBy, 80);
    if (phase === 'plan' && approver) {
      bits.push(t.approved(approver, shortDateTime(state.approvedAt)));
    }
    if (here) bits.push(t.here);
    out.push(bits.join(' '));
  });
  out.push('');

  // --- tasks
  if (tasks.length) {
    const counted = isDone || located || tracked;
    const doneCount = tasks.filter(isTaskDone).length;
    const skipNote = skipped.size ? ` · ${t.skippedCount(skipped.size)}` : '';
    const pendingNote = pending.size ? ` · ${t.pendingCount(pending.size)}` : '';
    const count = counted ? ` — ${t.doneOf(doneCount, tasks.length)}` : ` — ${tasks.length}`;
    out.push(`${t.tasksHeading}${count}${skipNote}${pendingNote}`);
    tasks.forEach((task, index) => {
      const title = `${task.id} · ${task.title}`;
      if (skipped.has(task.id)) {
        const reason = skipped.get(task.id);
        out.push(`- [ ] ~~${title}~~ — **${t.skipped}**${reason ? `: ${reason}` : ''}`);
        return;
      }
      if (pending.has(task.id)) {
        const question = pending.get(task.id);
        out.push(`- [ ] ⏸ ${title} — **${t.pendingAnswer}**${question ? `: ${question}` : ''}`);
        return;
      }
      const done = isTaskDone(task, index);
      const here = !isDone && current === task;
      out.push(`- [${done ? 'x' : ' '}] ${here ? `**${title}** ${t.here}` : title}`);
    });
    const cursor = codeSpan(state.buildCursor);
    if (!counted && cursor) {
      out.push('');
      out.push(t.cursorNotATask(cursor));
    }
    out.push('');
  } else if (codeSpan(state.buildCursor)) {
    out.push(t.tasksHeading);
    out.push(t.cursorNoTasks(codeSpan(state.buildCursor)));
    out.push('');
  }

  // --- questions
  out.push(t.questionsHeading);
  const questionsLink = questions ? link(t.questionsLink, questions, depth) : null;
  if (openQuestions > 0) {
    out.push(`${t.openQuestions(openQuestions)}${questionsLink ? ` — ${questionsLink}` : ''}`);
  } else if (questionsLink) {
    out.push(`${t.noneOpen} — ${questionsLink}`);
  } else {
    out.push(t.noneYet);
  }
  const pendingDecisions = Number(state.pendingDecisions);
  if (Number.isInteger(pendingDecisions) && pendingDecisions > 0) {
    out.push('');
    out.push(t.pendingDecisions(pendingDecisions));
  }
  out.push('');

  // --- everything else worth a click
  const others = Object.entries(artifacts)
    .filter(([key]) => !['idea', 'spec', 'plan', 'questions'].includes(key))
    .map(([key, value]) => link(plainText(key, 40), value, depth))
    .filter(Boolean);
  if (others.length) {
    out.push(t.otherArtifacts);
    out.push(others.join(' · '));
    out.push('');
  }

  const outcome = codeSpan(state.outcome);
  if (outcome) {
    const note = plainText(state.outcomeNote);
    out.push(t.outcome);
    out.push(`${outcome}${note ? ` — ${note}` : ''}`);
    out.push('');
  }

  return out.join('\n');
}

// --- writing it where it belongs -------------------------------------------

/** True when the file carries the note every generated page opens with. Read only
 *  from its head: the note is in the first lines, and a page is never large. */
function isGeneratedPage(file) {
  let fd;
  try {
    fd = fs.openSync(file, 'r');
    const head = Buffer.alloc(1024);
    const read = fs.readSync(fd, head, 0, head.length, 0);
    return head.toString('utf8', 0, read).includes(`\`${GENERATED_BY}\``);
  } catch {
    return false;
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
}

/** One file per run, and exactly one: any older name for the same slug goes, in the
 *  live folder and in the archive alike. Only `yyMMdd_<slug>.md` is ever removed, and
 *  only when this renderer wrote it: a file a person put in runs/ is theirs. */
function placeDocument({ liveDir, archiveDir, fileName, slug, body, archive, tail = '.md', protectExisting = false }) {
  // runs/ or runs/finished/ as a link would carry every write and delete below
  // somewhere else entirely.
  if (crossesLink(path.dirname(liveDir), archiveDir)) {
    throw new Error(`refusing to write under ${liveDir}: it goes through a link`);
  }
  const targetDir = archive ? archiveDir : liveDir;
  fs.mkdirSync(targetDir, { recursive: true });
  const target = assertInside(targetDir, path.join(targetDir, fileName));

  // A questions file written by hand holds answers nothing else holds. The run
  // page has always been overwritten, and still is; this one is not.
  if (protectExisting && exists(target) && !isGeneratedPage(target)) {
    throw new Error(`${path.basename(target)} was written by hand; not overwriting it`);
  }

  fs.writeFileSync(target, body, 'utf8');

  const ownName = datedName(slug, tail);
  for (const dir of [liveDir, archiveDir]) {
    if (!exists(dir)) continue;
    for (const name of fs.readdirSync(dir)) {
      if (!ownName.test(name)) continue;
      const stale = assertInside(dir, path.join(dir, name));
      if (stale !== target && isGeneratedPage(stale)) fs.unlinkSync(stale);
    }
  }
  return target;
}

// --- the questions page, from questions.json --------------------------------

/**
 * Generates a run's questions page from its questions.json, if it has one.
 *
 * Returns `{ used, file, open, error }`. `used` false means there is no
 * questions.json and the caller falls back to the hand-written page. When the
 * file is there but cannot be used - not JSON, not the right shape, or a page
 * written by hand already sits where the generated one would go - `error` says
 * why in terms of fields, never of values, the previous page is left exactly as
 * it was, and the open count is read from that page, so the run page stays true.
 *
 * Where the page goes follows the rule the agent used to apply by hand: under
 * questions/ while anything is open or the run is alive, moved to
 * questions/resolved/ once the run is finished and nothing is open.
 */
function renderQuestions({ file, docsDir, slug, prefix, isDone, lang }) {
  if (!exists(file)) return { used: false };
  const liveDir = path.join(docsDir, QUESTIONS_DIR);
  const archiveDir = path.join(liveDir, QUESTIONS_ARCHIVE);
  const fileName = `${prefix}_${slug}${QUESTIONS_SUFFIX}`;
  const previous = () => {
    for (const dir of [liveDir, archiveDir]) {
      const candidate = path.join(dir, fileName);
      if (exists(candidate)) return { used: true, file: candidate, open: countOpenQuestions(candidate) };
    }
    return { used: true, file: null, open: 0 };
  };

  let data;
  try {
    data = JSON.parse(fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, ''));
  } catch {
    return { ...previous(), error: 'questions.json is not valid JSON' };
  }
  const checked = questionsData.validateQuestions(data);
  if (!checked.ok) {
    return { ...previous(), error: `questions.json: ${checked.errors.slice(0, 10).join('; ')}` };
  }
  if (data.slug !== slug) return { ...previous(), error: 'questions.json: slug does not match the run folder' };

  const open = questionsData.openCount(data);
  const created = `20${prefix.slice(0, 2)}-${prefix.slice(2, 4)}-${prefix.slice(4, 6)}`;
  const body = questionsData.renderQuestionsMarkdown(data, { lang, created });
  try {
    const placed = placeDocument({
      liveDir,
      archiveDir,
      fileName,
      slug,
      body,
      archive: isDone && open === 0,
      tail: QUESTIONS_SUFFIX,
      protectExisting: true,
    });
    return { used: true, file: placed, open };
  } catch (error) {
    return { ...previous(), error: error.message };
  }
}

// --- the feed for the panel --------------------------------------------------
//
// The panel shows the runs of every project on this machine, and it must never
// read or write a docs folder - that is the promise that the documentation is
// written by task-flow alone. So instead of the panel going to the projects,
// every render leaves a summary of the project where the panel looks: one file
// per project in <home>/feed/ (config.js homeDir). The panel reads nothing else.
//
// What goes in is what the panel shows, in closed shapes: the same discipline as
// the run page, because a state.json is repository data and the panel is a web
// page. The absolute docs folder does NOT go in - the panel has no use for it,
// and not knowing it is part of why the panel cannot write there.

const FEED_PHASES = [...PHASES, 'done'];
const TASK_ID = /^T[0-9]+[a-z]?$/;
const ISO = /^\d{4}-\d{2}-\d{2}T[\d:.]+(Z|[+-]\d{2}:\d{2})?$/;
const clip = (value, max) => (typeof value === 'string' ? plainText(value, max) : null);
const iso = (value) => (typeof value === 'string' && ISO.test(value.trim()) ? value.trim() : null);

/** One run, as the panel sees it. */
function feedRun({ entry, state, stateRoot, docsDir, statePath }) {
  const planPath = resolveInsideDocs(docsDir, state.artifacts && state.artifacts.plan);
  const tasks = readPlanTasks(planPath).map((task) => ({ id: task.id, title: task.title, done: task.ticked }));
  const idList = (value, textKey, max) =>
    (Array.isArray(value) ? value : [])
      .filter((item) => item && typeof item.id === 'string' && TASK_ID.test(item.id))
      .slice(0, 100)
      .map((item) => ({ id: item.id, [textKey]: clip(item[textKey], max) }));

  // The questions go in whole when the run keeps them as data - the panel turns
  // them into cards - and only as a count when they are a page written by hand.
  let questions;
  const questionsFile = path.join(stateRoot, entry, 'questions.json');
  if (exists(questionsFile)) {
    let data = null;
    try {
      data = JSON.parse(fs.readFileSync(questionsFile, 'utf8').replace(/^﻿/, ''));
    } catch {
      data = null;
    }
    questions =
      data && questionsData.validateQuestions(data).ok && data.slug === entry
        ? { source: 'json', items: data.items, consumedSubmissions: data.consumedSubmissions || [] }
        : { source: 'invalid' };
  } else {
    const legacy = findQuestionsFile(docsDir, entry, state);
    questions = { source: 'legacy', open: legacy ? countOpenQuestions(legacy.file) : 0 };
  }

  // The run page, relative to the docs folder, for the panel to show as a path.
  const prefix = runCreatedPrefix(state, statePath);
  const pageName = `${prefix}_${entry}.md`;
  const runPage = [path.join(RUNS_DIR, pageName), path.join(RUNS_DIR, RUNS_ARCHIVE, pageName)]
    .find((relative) => exists(path.join(docsDir, relative)));

  const phase = FEED_PHASES.includes(state.phase) ? state.phase : null;
  return {
    slug: entry,
    phase,
    status: ['running', 'blocked', 'failed', 'done'].includes(String(state.status || '').toLowerCase())
      ? String(state.status).toLowerCase()
      : 'paused',
    mode: String(state.mode || '').trim().toLowerCase() === 'auto' ? 'auto' : 'attended',
    created: `20${prefix.slice(0, 2)}-${prefix.slice(2, 4)}-${prefix.slice(4, 6)}`,
    updated: iso(state.updated),
    phaseChangedAt: iso(state.phaseChangedAt),
    buildCursor: typeof state.buildCursor === 'string' && TASK_ID.test(state.buildCursor) ? state.buildCursor : null,
    tasks,
    pendingTasks: idList(state.pendingTasks, 'question', 300),
    skippedTasks: idList(state.skippedTasks, 'reason', 200),
    branch: clip(state.branch, 120),
    pr: linkTarget(state.pr),
    runPage: runPage ? runPage.split(path.sep).join('/') : null,
    questions,
  };
}

/**
 * Writes <home>/feed/<projectKey>.json for this project, atomically (a temp file
 * renamed over the old one, so the panel never reads half a file).
 *
 * Returns the file written, or throws. The caller treats a throw as a note, not a
 * failure: the feed is for the panel, and a machine without a usable home folder
 * must still get its documentation rendered.
 *
 * Refused outright when the home folder sits inside the project or inside the
 * docs folder - a feed there would put the panel's reading, and its answers,
 * where the promise says it has no business.
 */
function writeFeed({ projectDir, config, docsDir }) {
  const home = homeDir();
  if (isInside(projectDir, home) || isInside(home, projectDir)) {
    throw new Error('the local state folder and the project overlap');
  }
  if (isInside(docsDir, home) || isInside(home, docsDir)) {
    throw new Error('the local state folder and the docs folder overlap');
  }

  const runs = [];
  for (const entry of fs.readdirSync(config.stateDir)) {
    if (!SAFE_SEGMENT.test(entry)) continue;
    const statePath = path.join(config.stateDir, entry, 'state.json');
    if (!exists(statePath)) continue;
    try {
      const state = readJson(statePath);
      if (!state || typeof state !== 'object' || Array.isArray(state)) continue;
      runs.push(feedRun({ entry, state, stateRoot: config.stateDir, docsDir, statePath }));
    } catch {
      runs.push({ slug: entry, unreadable: true });
    }
  }

  const key = projectKey(projectDir);
  const feedDir = homePath(['feed']);
  fs.mkdirSync(feedDir, { recursive: true });
  const file = homePath(['feed', `${key}.json`]);
  const body = {
    version: 1,
    projectKey: key,
    projectDir: path.resolve(projectDir),
    projectName: path.basename(path.resolve(projectDir)),
    language: config.pageLanguage || 'en',
    generatedAt: new Date().toISOString(),
    runs,
  };
  const temp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(temp, JSON.stringify(body, null, 2) + '\n', 'utf8');
  fs.renameSync(temp, file);
  return file;
}

// --- the run over all runs -------------------------------------------------

/**
 * Renders every run of a project. `docsDir` overrides the configured folder (for
 * the CLI and the tests); the language always comes from the configuration.
 */
function renderAll({ projectDir, docsDir, slug } = {}) {
  const root = projectDir || process.env.CLAUDE_PROJECT_DIR || process.cwd();
  const result = { rendered: [], archived: [], skipped: [], questionErrors: [] };

  const loaded = loadConfig(root);
  if (!loaded.exists) {
    result.skipped.push({ run: '(project)', why: 'no .claude/task-flow.json - not a task-flow project' });
    return result;
  }
  const config = loaded.config || {};
  const targetDocs = docsDir ? path.resolve(docsDir) : config.docsDir;
  if (!targetDocs || !config.stateDir || (!docsDir && !loaded.ok)) {
    result.skipped.push({ run: '(project)', why: `configuration is not valid: ${loaded.errors.join('; ')}` });
    return result;
  }
  if (!exists(targetDocs)) {
    result.skipped.push({ run: '(project)', why: `docs folder not found: ${targetDocs}` });
    return result;
  }
  const lang = config.pageLanguage || 'en';

  const stateRoot = config.stateDir;
  if (!exists(stateRoot)) {
    result.skipped.push({ run: '(project)', why: `no runs under ${path.relative(root, stateRoot)}` });
    return result;
  }

  const liveDir = path.join(targetDocs, RUNS_DIR);
  const archiveDir = path.join(liveDir, RUNS_ARCHIVE);

  for (const entry of fs.readdirSync(stateRoot)) {
    if (slug && entry !== slug) continue;
    const statePath = path.join(stateRoot, entry, 'state.json');
    if (!exists(statePath)) continue;

    try {
      if (!SAFE_SEGMENT.test(entry)) throw new Error(`run directory ${JSON.stringify(entry)} is not a safe name`);

      const state = readJson(statePath);
      const isDone = state.phase === 'done' || String(state.status || '').toLowerCase() === 'done';
      const prefix = runCreatedPrefix(state, statePath);

      // A run with a questions.json gets its questions page generated from it; a
      // run without one keeps the page its agent wrote by hand, as before.
      let questions = null;
      let openQuestions = 0;
      const structured = renderQuestions({
        file: path.join(stateRoot, entry, 'questions.json'),
        docsDir: targetDocs,
        slug: entry,
        prefix,
        isDone,
        lang,
      });
      if (structured.error) result.questionErrors.push({ run: entry, why: structured.error });
      if (structured.used) {
        questions = structured.file ? { file: structured.file } : null;
        openQuestions = structured.open;
      } else {
        questions = findQuestionsFile(targetDocs, entry, state);
        openQuestions = questions ? countOpenQuestions(questions.file) : 0;
      }
      const archive = isDone && openQuestions === 0;

      const depth = archive ? 2 : 1;
      const planPath = resolveInsideDocs(targetDocs, state.artifacts && state.artifacts.plan);

      // Only artifacts that really sit in the docs folder become links. Some runs
      // record repository paths here (.claude/reviews/...), and a link to a file
      // that is not there is noise dressed as information.
      //
      // What is kept is the path RELATIVE TO THE DOCS FOLDER, recomputed from the
      // resolved file rather than copied from state.json. The link is built by
      // putting `../` in front of it, so an absolute path pasted straight through
      // would produce a link that resolves nowhere. Recomputing also flattens
      // `./a/../b` spellings to one form.
      const artifacts = {};
      for (const [key, value] of Object.entries(state.artifacts || {})) {
        const resolved = resolveInsideDocs(targetDocs, value);
        if (resolved && exists(resolved)) artifacts[key] = path.relative(targetDocs, resolved);
      }

      const body = buildDocument({
        state,
        slug: entry,
        tasks: readPlanTasks(planPath),
        questions: questions ? path.relative(targetDocs, questions.file) : null,
        openQuestions,
        depth,
        artifacts,
        created: `20${prefix.slice(0, 2)}-${prefix.slice(2, 4)}-${prefix.slice(4, 6)}`,
        lang,
      });

      const file = placeDocument({
        liveDir,
        archiveDir,
        fileName: `${prefix}_${entry}.md`,
        slug: entry,
        body,
        archive,
      });

      (archive ? result.archived : result.rendered).push({ run: entry, file });
    } catch (error) {
      // One bad run must never hide the others, and must never take the caller down.
      result.skipped.push({ run: entry, why: error.message });
    }
  }

  // The panel's summary of this project. Never at the documentation's expense:
  // whatever goes wrong here is reported and the render still counts as done.
  try {
    result.feed = writeFeed({ projectDir: root, config, docsDir: targetDocs });
  } catch (error) {
    result.feedError = error.message;
  }

  return result;
}

module.exports = {
  renderAll,
  PHASES,
  STRINGS,
  RUNS_DIR,
  RUNS_ARCHIVE,
  QUESTIONS_DIR,
  QUESTIONS_ARCHIVE,
  buildDocument,
  readPlanTasks,
  countOpenQuestions,
  renderQuestions,
  writeFeed,
  assertInside,
  runCreatedPrefix,
};

// --- CLI -------------------------------------------------------------------

if (require.main === module) {
  const argv = process.argv.slice(2);
  const value = (flag) => {
    const index = argv.indexOf(flag);
    return index >= 0 ? argv[index + 1] : undefined;
  };

  const outcome = renderAll({
    projectDir: value('--project-dir'),
    docsDir: value('--docs-dir'),
    slug: value('--slug'),
  });

  if (!argv.includes('--quiet')) {
    for (const item of outcome.rendered) process.stdout.write(`rendered  ${item.run}  -> ${item.file}\n`);
    for (const item of outcome.archived) process.stdout.write(`archived  ${item.run}  -> ${item.file}\n`);
    for (const item of outcome.skipped) process.stdout.write(`skipped   ${item.run}  (${item.why})\n`);
    if (!outcome.rendered.length && !outcome.archived.length) process.stdout.write('nothing rendered.\n');
  }
  // Even with --quiet: the agent runs this right after writing questions.json,
  // and a file it got wrong must not pass in silence.
  for (const item of outcome.questionErrors) process.stderr.write(`questions ${item.run}: ${item.why}\n`);
  if (outcome.questionErrors.length) process.exitCode = 1;
  // A note, not a failure: the documentation was rendered either way.
  if (outcome.feedError) process.stderr.write(`panel feed not written: ${outcome.feedError}\n`);
}
